### ISSUE TITLE
Review workflow description

### ISSUE THREAD

**Issue by ktoddbrown** [ktoddbrown/SoilDRaH#13]
Review the workflow description for clarity. What is done well and what could be more clear?

https://github.com/ktoddbrown/SoilDRaH/wiki/Workflow-for-new-data-addition

**Comment by GabrielThrasher** [comment]
What is done well:
- The usage of verbs (typically the first word in each "box") is really helpful at cementing what the reader needs to do to complete each task. Also, keeps the table engaging as the same verb is not used for every "box".
- The links to the "Annotation" and "Read script" paper streamlines the table and leaves no ambiguity as to what the reader needs to read for more explanation/context. 
- Now this is more of a small thing, but I really like how the rows alternate between the two different shades of gray. It helps a first-time reader to be able to properly follow/read the table by showing the direction and making sure they don't accidentally read a different row.

What could be more clear:
- There seem to be _no_ style or writing issues, and given the context (the scope, purpose, and target audience of the table) I believe the documentation to be in, there seem to also be _no_ clarity issues present. 

Overall, I feel like the table is well-written: it gives the reader clear step-by-step instructions for the workflow of adding data to the dataset.
