### ISSUE TITLE
Create templates

### ISSUE THREAD

**Issue by ktoddbrown** [ktoddbrown/SoilDRaH#2]
Build out templates for reading and generating annotations.

**Comment by ktoddbrown** [comment]
- [ ] Add in the old transformLong code from the previous repository here: https://github.com/ktoddbrown/SoilDRaH/blob/f70b80b6199b157aefd44ad9e15f48d9f47c312f/R/readTemplate.R#L48

**Comment by ktoddbrown** [comment]
@ursapillay I went through and suggested a little more 'why' focus on the vignettes/readTemplate.Rmd Could you go through and build this out a little more. I think we are close!

**Comment by ursapillay** [comment]
@ktoddbrown I just revised vignettes/readTemplate.Rmd a bit
